package com.planatech.embertask.common

const val ARTICLE_TITLE = "ARTICLE_TITLE"
const val ARTICLE_AUTHOR = "ARTICLE_AUTHOR"
const val ARTICLE_CONTENT = "ARTICLE_CONTENT"
const val ARTICLE_SOURCE_URL = "ARTICLE_SOURCE_URL"
const val ARTICLE_SOURCE_NAME = "ARTICLE_SOURCE_NAME"
const val ARTICLE_IMAGE_URL = "ARTICLE_IMAGE_URL"